### PR TITLE
Add support for Zendesk Inbox

### PR DESCRIPTION
**Pull request by takeo**
Zendesk Inbox recently moved to a wysiwyg editor that uses an iframe, so I updated this with the same special tweaks that other sites with iframe based editors have.

### CODE REVIEW

**Comment by carlinyuen** [comment]
Thanks Toby! Let me check this out and get back to you this week.

.C

**Comment by carlinyuen** [comment]
Hey Toby, this looks pretty good! Have you tested this by any chance? If not, I'll try to get around to testing it this weekend and then doing the official merge if all looks well. Figured you may be better positioned to test it if you already have access to ZenDesk and such.

**Comment by takeo** [comment]
Hey @carlinyuen, yup, it's working. Here's a gif of me using it with my PR version of the extension installed in my Chrome:



It's using TinyMCE, so it's pretty much the exact same setup (and behavior, I assume) as atlassian.net

**Comment by carlinyuen** [comment]
Awesome. I'll pull it in and push an update this weekend, much appreciated!


*. Carlin*
............................................
Product . Design . Development
e : email.me@carlinyuen.com
# : +1 (234) 567-9763

**Pull request merged**
